"""
Django settings for modbus_controller project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

MODBUS_TEMPLATE_FOLDER = "modbus_templates"
EXTRA_DJANGO_TEMPLATES = "django_templates"
LOGS_FOLDER = "logs"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR,MODBUS_TEMPLATE_FOLDER) # the modbus xml templates
CONTROL_TEMPLATES = os.path.join(BASE_DIR, "controller_setup/templates")
BASE_TEMPLATES = os.path.join(BASE_DIR, "modbus_controller/templates")
LOGS_DIR = os.path.join(BASE_DIR, LOGS_FOLDER)

MEDIA_ROOT = os.path.join(BASE_DIR, MODBUS_TEMPLATE_FOLDER)
MEDIA_URL = '/media/' #TODO: change?
STATIC_URL = '/static/'
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout/'
LOGIN_REDIRECT_URL = '/index/'

# follow https://docs.webfaction.com/software/django/getting-started.html
STATIC_ROOT = '/home/enerwhere/webapps/modbus_controller_static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "modbus_controller/static/modbus_controller"),
]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ndq_+jne6o$hdhywar_%@9y3c%n%f9-*h#jlsidgzani6_v3z^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [".mohkof1106.tk",]


# Sending emails
"""
Servers:

    POP (for receiving) - mail.webfaction.com
    IMAP (for receiving) - mail.webfaction.com
    SMTP (for sending) - smtp.webfaction.com

Ports:

          Standard     Secure (SSL)     Secure (TLS)
    POP     110     995      
    IMAP     143     993      
    SMTP     25     465     587
"""
EMAIL_HOST = "smtp.webfaction.com"
EMAIL_PORT = "587"
EMAIL_HOST_USER = "controller"
EMAIL_HOST_PASSWORD = "controller_test"
EMAIL_SENDER = "Modbus Controller"
DEFAULT_FROM_EMAIL = EMAIL_SENDER + " <mohkof1106@gmail.com>"

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'controller_setup',
    'chronograph',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'modbus_controller.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_TEMPLATES, CONTROL_TEMPLATES],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'modbus_controller.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'configuration.sqlite3'),
    }
}

# Logging for Django
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'live_control.log'),
            'formatter': 'verbose'
        },
        'records': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'records.log'),
            'formatter': 'verbose'                    
        },
        'live_rotation': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'live_control.log'),
            'formatter': 'verbose',
            'backupCount': 10,
            'maxBytes': 100000000 # 100MB
        },
    },
    'loggers': {
        'django': {
            'handlers': ['live_rotation'],
            'propagate': True,
            'level': 'INFO',
        },
        'live_control': {
            'handlers': ['live_rotation'],
            'level': 'INFO',
        },
        'recorder' : {
            'handlers': ['records'],
            'level': 'INFO',                      
        },
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


if os.path.isfile(os.path.join(BASE_DIR, "modbus_controller/settings_local.py")):
    from settings_local import *
